pipeline:
  identifier: Build_manasi_das_Test_Ansible_001_1707906197447
  name: Build Test-Ansible-001
  orgIdentifier: default
  projectIdentifier: Test01
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: manasi-das/Test-Ansible-001
  stages:
    - parallel:
        - stage:
            identifier: build
            name: build
            spec:
              cloneCodebase: true
              execution:
                steps:
                  - step:
                      identifier: echo
                      name: echo
                      spec:
                        shell: Bash
                        command: echo hello world
                      timeout: ""
                      type: Run
                  - step:
                      type: Run
                      name: Run_2
                      identifier: Run_2
                      spec:
                        shell: Bash
                        command: hostname
                  - step:
                      type: Plugin
                      name: Plugin_1
                      identifier: Plugin_1
                      spec:
                        connectorRef: account.harnessImage
                        image: plugin/slack
              platform:
                arch: Amd64
                os: Linux
              runtime:
                spec: {}
                type: Docker
            type: CI
        - stage:
            name: Ansible1
            identifier: Ansible1
            description: ""
            type: CI
            spec:
              cloneCodebase: true
              platform:
                os: Linux
                arch: Amd64
              runtime:
                type: Docker
                spec: {}
              execution:
                steps:
                  - step:
                      type: BuildAndPushDockerRegistry
                      name: BuildAndPushDockerRegistry_1
                      identifier: BuildAndPushDockerRegistry_1
                      spec:
                        connectorRef: account.harnessImage
                        repo: mdasmrvcloud84/test-ansible-001
                        tags:
                          - test-ansible-001
                      when:
                        stageStatus: All
  delegateSelectors:
    - docker-delegate
